### ISSUE TITLE
Allow rules for what is considered a teamkill to be configurable in the plugin

### ISSUE THREAD

**Issue by REALMWTH** [PatPeter/FriendlyFireAutoban#1]
I suggest you to re-write banning algorythm so mass teamkill could be detected.
So if player 1 kills fellow player 2 and fellow player 3 within time < 5 seconds then ban triggers.
That's how mass spawn and lift kills would be detected.

**Comment by Rnen** [comment]
Should be a walk in the park really, just start a timer on the player's first kill, if it detects another one it adds it to a int and adds time to the timer. If the timer expires and they're over a certain limit, `BAN`
Would do it myself, but im litterally moving tomorrow, so got no time

**Comment by PatPeter** [comment]
@realmbmc I'm working on recoding all of my plugins to be compatible with Smod3 tonight. 

@Rnen No worries! I'd feel bad if I barely put any effort into my own plugin.

**Comment by REALMWTH** [comment]
@PatPeter great news!
Consider write flexible config to define which classes are defined as "fellow".
For example, I want ban system trigger when CI kills CI but don't when Class D kills Class D.
Dictionary:

> teamkill_ban_roles: 1:1, 2:2, 3:3

1:1, 2:2, 3:3 are classids

I will help you with the plugin and will make a few pull requests in a few days,

**Comment by PatPeter** [comment]
@realmbmc That change is pretty easy. I had to get an if statement hack out to my server because a bunch of Chaos were killing d-class, but I can easily add a config for that.

**Comment by realmbmc** [comment]
Any news about adding kill timer?

**Comment by PatPeter** [comment]
@realmbmc I made the issue's name more specific and since the autoban matrix is implemented, I'm going to close the issue. If you still need the friendly fire gain/loss on timer tick, please create a new issue.
