### ISSUE TITLE
Personal broadcast warning when you're close to being banned

### ISSUE THREAD

**Issue by NeonWizard** [PatPeter/FriendlyFireAutoban#18]
When someone is close to getting auto-banned, send them a personal broadcast warning to let them know.

**Comment by PatPeter** [comment]
Broadcasts can only be global, not personal, but I was planning this for version 3 of Friendly Fire Autoban!

**Comment by NeonWizard** [comment]
Uhh no, personal broadcasts were introduced to smod a while ago. It would be very easy to implement quickly

**Comment by PatPeter** [comment]
It's in ServerMod2 as a command, `PBC`, but it isn't in the API last I checked coding my `callvote` plugin.

```
API
    Added Map.Broadcast function. Takes a uint for the duration, a string for the message that should be displayed and a bool for whether or not it should be monospaced. This allows you to display a message for all your players, similar to the BC command.
    Added Map.ClearBroadcasts function. This allows you to empty the queue of messages to broadcast, similar to the BCCLEAR command.
```

https://github.com/Grover-c13/Smod2/releases

**Comment by NeonWizard** [comment]
Yeah it wouldn’t be in the Map API considering it’s not something that runs on a global scale. There’s a personal broadcast method in the Player API, can’t remember what it’s called rn

**Comment by PatPeter** [comment]
I'll look into it an add it to the next version. I have to rewrite how TKs are counted for #17 but in the long run it will allow the plugin to work like it would in other games. I wish they had listed the Player API updates in the same announcement.

**Comment by PatPeter** [comment]
Well derp I thought I updated the Smod2.dll for FFA but it turns out I hadn't. That explains why it wasn't showing up in peek definition. I'm hoping to get this change out tonight.

**Comment by PatPeter** [comment]
Issue #8 has also been closed in lieu of using broadcasts instead

**Comment by PatPeter** [comment]
Deserves its own issue.

**Comment by PatPeter** [comment]
Has been implemented since version 4.
