### ISSUE TITLE
Friendly fire gain/loss on timer tick.

### ISSUE THREAD

**Issue by REALMWTH** [PatPeter/FriendlyFireAutoban#2]
We need implemented FF gain and loss on timer tick. For example, if player has killed another player with the same (or custom defined) friendly role then server should start <CUSTOM_INT> seconds timer. If player kills another player within <CUSTIOM_INT> seconds then autoban should trigger.

**Comment by PatPeter** [comment]
I'm going to make it so that this is one of three modes that can be chosen between in the plugin.

**Comment by PatPeter** [comment]
Timers have now been added to version 2.0.0 of Friendly Fire Autoban! Please check them out.

**Comment by REALMWTH** [comment]
Sure! I will report if there are any issues. Thanks for release! You're awesome.

**Comment by PatPeter** [comment]
There's currently a bug in friendly fire forgiveness in system number 2 where only the most recently friendly fire instance would be forgiven, and then the timer will stop. I've made a fix to make it so that all instances of friendly fire will be forgiven that will be in the next update.

**Comment by PatPeter** [comment]
This friendly fire autoban system is confirmed working with 2.1.*.
