### ISSUE TITLE
LINQ failure in tks command and output bug in teamkill logging

### ISSUE THREAD

**Issue by ITeMbI4** [PatPeter/FriendlyFireAutoban#23]
![image](https://user-images.githubusercontent.com/46756889/54947501-25f92980-4f43-11e9-8eca-31fef4301ea6.png)
![image](https://user-images.githubusercontent.com/46756889/54947524-31e4eb80-4f43-11e9-9496-814ba8729aec.png)

**Comment by PatPeter** [comment]
Alright, this issue has been fixed in version 3.0.1. Thank you very much for reporting!!!
