### ISSUE TITLE
Friendly Fire ban at end of round, scales ban time based on # of kills

### ISSUE THREAD

**Issue by PatPeter** [PatPeter/FriendlyFireAutoban#4]
If I add this, I'll be adding it in addition to request #2 so that admins will have three optional systems for managing friendly fire.

**Comment by REALMWTH** [comment]
Great news! Thanks for such effort!

**Comment by PatPeter** [comment]
I mistakenly referenced issue 3 in my Git commit message, but it's worth mentioning that this banning system is also now present in Friendly Fire Autoban Version 2.0.0.

**Comment by REALMWTH** [comment]
Thanks for release! Close this issue. I can't :)

**Comment by PatPeter** [comment]
I've done close to no testing for either of the new ban systems I put in place, so until I know for a fact that they work I won't be closing them.

**Comment by PatPeter** [comment]
I've actually put off testing this system to any acceptable degree but now I'll be converted all of my servers over to it so I have to.

**Comment by PatPeter** [comment]
Now that I've actually tested this system I can confirm that it works. Closing.
